Support Laravel 7.x
biscolab/laravel-recaptcha pull request #37
Opened 2020-03-03 20:07 UTC by jerodev

No parts vital to this package have been changed in Laravel 7. 
Support for the latest version should work out of the box.

2020-03-04 15:03 UTC, MrReeds commented
+1

2020-03-05 06:42 UTC, MrReeds requested changes
update readme file to show support for laravel 7

2020-03-06 16:10 UTC, matthewhaworth commented
Keen to see this merged! :)

2020-03-06 18:35 UTC, MrReeds approved these changes
my approval

2020-03-06 23:28 UTC, closed without merging